### ISSUE TITLE
Python Version Inconsistence Problem

### ISSUE THREAD

**Issue by Elaine9010** [Alacarter/deltaco#1]
I would like to install open-clip, which required python>=3.7, but deltaco is developed on python=3.6.5. How to resolve the problem? Thanks :)

**Comment by Alacarter** [comment]
Deltaco's python code should be able to run with python3.7 with very minimal (or no) code changes, though some of the packages in our requirements.txt may need to be upgraded to a slightly later version to be compatible with python3.7.

I am looking at the [requirements.txt in open-clip](https://github.com/mlfoundations/open_clip/blob/main/requirements.txt). Are you having trouble installing a package specifically that conflicts with deltaco's packages?

**Comment by Alacarter** [comment]
Seems resolved based on #2.
