### ISSUE TITLE
success rate calculation

### ISSUE THREAD

**Issue by Elaine9010** [Alacarter/deltaco#2]
Hello, I ran the command for replicating results in your repo, but failed to find successs rate in the  exp_logs folder. Could you share with us how to get the success rate?

**Comment by Alacarter** [comment]
The experiment, if running successfully, will create two layers of subdirectories under your `LOCAL_LOG_DIR`  (described [here](https://github.com/Alacarter/deltaco#setting-up)). In the deepest subdirectory corresponding to your exp run, you will see a progress.csv file with a column named `eval/env_infos/final/rewards Mean` which will contain the success rates you are looking for. Each row is the value of that column metric for a given epoch number.

Note that the eval is only run every 10 epochs, so when plotting it, a lot of the eval metrics will look like "step functions" that only update every 10 epochs.

**Comment by Elaine9010** [comment]
![Screenshot from 2023-07-04 22-53-00](https://github.com/Alacarter/deltaco/assets/77252889/cebb2e70-d38f-4b22-9c6d-19e9df4d3b88)
Do you mean column N ? After 300 epochs this value ends up being 0.02696. But I don't see how that can be related to the success rate. THis is the result of scenario A with CNN as demo encoder, miniLM as language encoder.

**Comment by Alacarter** [comment]
Not quite column N, since that is the average total reward over the entire trajectory, instead of showing the proportion of trajectories that succeeded on the last timestep. If you don't have a column called `eval/env_infos/final/rewards Mean`, could you make sure you are on the latest commit (with the May 29 update)?

**Comment by Elaine9010** [comment]
OK I see, I'll try with the latest update. Thanks for helping.

**Comment by Alacarter** [comment]
marking as resolved!
